### ISSUE TITLE
Swoole\Coroutine\MySQL 'select sleep(1)'返回false?

### ISSUE THREAD

**Issue by hncg** [swoole/swoole-src#1946]
1 现象：select sleep(1)返回false。结果如下:
```
array(1) {
  [0]=>
  array(1) {
    ["sleep(0)"]=>
    string(1) "0"
  }
}
string(15) "select sleep(0)"
bool(false)
string(15) "select sleep(7)"
bool(false)
string(15) "select sleep(9)"
bool(false)
string(15) "select sleep(5)"
bool(false)
string(15) "select sleep(6)"
bool(false)
string(15) "select sleep(8)"
bool(false)
string(15) "select sleep(1)"
bool(false)
string(15) "select sleep(2)"
bool(false)
string(15) "select sleep(4)"
bool(false)
string(15) "select sleep(3)"

```
2 重现代码：
```
<?php
$count = 10;
while ($count--) {
    go(function() use ($count) {
        test($count);
    });
}


function test($name)
{
    $swoole_mysql = new Swoole\Coroutine\MySQL();
    $ret = $swoole_mysql->connect([
        'host' => 'mysql-test',
        'port' => 3306,
        'user' => 'root',
        'password' => '123456',
        'database' => 'sys',
    ]);
    if (!$ret) {
        return;
    }
    $sql = "select sleep({$name})";
    var_dump($swoole_mysql->query($sql), $sql);
}
```

3 重现命令:
```
3.1 启动容器 docker-compose up 
3.2 进入容器 sudo docker exec -it swoole bash //mac 无需sudo
3.3 php ~/test.php
```
4 docker-compose.yaml文件:
```
mysql-test:
  container_name: "mysql-test"
  hostname: "mysql-test"
  image: "mysql:5.7.20"
  environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=123456
  ports:
    - "3306:3306"

swoole:
  container_name: "swoole"
  hostname: "swoole"
  image: "registry.cn-qingdao.aliyuncs.com/hncg/swoole:4.1.1"
  links:
    - mysql-test:mysql-test
  environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=123456
  tty: true
```
